"""Initial migration

Revision ID: 1d46ea197d33
Revises: 1eac8acb27e1
Create Date: 2024-11-05 18:28:34.492840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d46ea197d33'
down_revision: Union[str, None] = '1eac8acb27e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PerevalAdded')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PerevalAdded',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('column1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('column2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PerevalAdded_pkey')
    )
    # ### end Alembic commands ###
