"""Initial migration

Revision ID: ec21046bc949
Revises: 86a3eea61d0c
Create Date: 2024-11-07 11:28:06.966229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec21046bc949'
down_revision: Union[str, None] = '86a3eea61d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pereval', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pereval', 'image', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pereval', type_='foreignkey')
    op.drop_column('pereval', 'image_id')
    # ### end Alembic commands ###
